=== alibooresh/social_media_with_custom_orm/src/main/resources/entities.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://www.ali.com/orm">
    <xs:element name="entities">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entity" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="name"/>
                                            <xs:attribute type="xs:string" name="type"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="columns">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="column" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="name" use="optional"/>
                                                        <xs:attribute type="xs:string" name="type" use="optional"/>
                                                        <xs:attribute type="xs:boolean" name="unique" use="optional"/>
                                                        <xs:attribute type="xs:boolean" name="nullable" use="optional"/>
                                                        <xs:attribute type="xs:integer" name="length" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="manyToOne" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="name" use="required"/>
                                                        <xs:attribute type="xs:string" name="type" use="required"/>
                                                        <xs:attribute type="xs:string" name="targetEntity"
                                                                      use="required"/>
                                                        <xs:attribute type="xs:boolean" name="unique" use="optional"
                                                                      default="false"/>
                                                        <xs:attribute type="xs:boolean" name="nullable" use="optional"
                                                                      default="true"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="table"/>
                        <xs:attribute type="xs:string" name="entityClass"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alibooresh/social_media_with_custom_orm/src/main/resources/entities.xml
<?xml version="1.0" encoding="UTF-8" ?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.ali.com/orm"
          xsi:schemaLocation="http://www.ali.com/orm entities.xsd">
    <entity table="user" entityClass="com.hugsy.socialmedia.model.User">
        <id name="id" type="java.lang.Long"/>
        <columns>
            <column name="name" type="java.lang.String"/>
            <column name="username" type="java.lang.String" unique="true" length="50" nullable="false"/>
        </columns>
    </entity>
    <entity table="post_tbl" entityClass="com.hugsy.socialmedia.model.Post">
        <id name="id" type="java.lang.Long"/>
        <columns>
            <column name="caption" type="java.lang.String" unique="false" nullable="false" length="500"/>
            <column name="media_url" type="java.lang.String" unique="false" nullable="false" length="1000"/>
        </columns>
    </entity>
</entities>
